#!/usr/bin/python
# 
# Simple program to get the current value of a cryptocurrency from Bittrex.com
# 
# Arguments:
# -u            Format output as USD/fiat (2 decimal places)
# -b            Format output as BTC/satoshi (8 decimal places)
# -m <market>   Which market to show (e.g. "btc-ltc")

import sys
import requests
import argparse
import json
from bittrex import Bittrex

base_url = 'https://bittrex.com/api/v1.1/'

def getticker(market):
    url = base_url + 'public/getticker?market=' + market
    response = requests.get(url)

    if response.status_code != 200:
        raise ApiError('GET /getmarkets/ {}'.format(response.status_code))
    
    market = response.json()
    return market['result']['Last']

def main(argv):
    market = ''

    with open("secrets.json") as secrets_file:
        secrets = json.load(secrets_file)
        secrets_file.close()
    bittrex = Bittrex(secrets['key'], secrets['secret'])

    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest = 'command', help = 'Which action to perform')

    # ticker command
    parser_ticker = subparsers.add_parser('ticker', help = 'Show a ticker')
    parser_ticker.add_argument("basecurrency", help="Base currency symbol (e.g. BTC)")
    parser_ticker.add_argument("marketcurrency", help="Market currency symbol (e.g. NEO)")
    group = parser_ticker.add_mutually_exclusive_group()
    group.add_argument("-f", help="Format output as fiat (2 decimal places) (default)", action="store_true", default=True)
    group.add_argument("-s", help="Format output as satoshi (8 decimal places)", action="store_true", default=False)

    # wallet command
    parser_wallet = subparsers.add_parser('wallet', help = 'Show info about a wallet in your account')
    parser_wallet.add_argument("wallet", help="Which wallet to show.")

    # balances command
    parser_balances = subparsers.add_parser('balances', help = 'Show all balances in your account')
    parser_balances.add_argument("-n", help = 'Show only wallets with non-zero balance', action = "store_true", default = False)

    # order history command
    parser_orderhistory = subparsers.add_parser('orderhistory', help = 'Show recent order history for your account')
    parser_orderhistory.add_argument("market", help = 'Show order history only for this market (optional)', nargs='?', action = "store", default = 'all')

    # open orders command
    parser_openorders = subparsers.add_parser('openorders', help = 'Show open orders in your account')
    parser_openorders.add_argument("market", help = 'Show open orders only for this market (optional)', nargs='?', action = "store", default = 'all')

    args = parser.parse_args()
    

    if args.command == 'ticker':
        market = args.basecurrency + '-' + args.marketcurrency
        result = getticker(market)

        if args.s:
            args.f = False
            print('{:.8f}'.format(result))
        if args.f:
            print('{:.2f}'.format(result))

    if args.command == 'wallet':
        out = json.loads(json.dumps(bittrex.get_balance(args.wallet)))
        #print(json.dumps(out, indent=4, sort_keys=True))
        print("Currency:  ", out['result']['Currency'])
        print("Balance:   ", out['result']['Balance'])
        print("Available: ", out['result']['Available'])

    if args.command == 'balances':
        out = json.loads(json.dumps(bittrex.get_balances()))
        for x in out['result']:
            if args.n:
                if x['Balance'] > 0:
                    doprint = True;
                else:
                    doprint = False
            else:
                doprint = True

            if doprint:
                print("Currency:  ", x['Currency'])
                print("Balance:   ", x['Balance'])
                print("Available: ", x['Available'])
                print()

    if args.command == 'orderhistory':
        if args.market == 'all':
            out = json.loads(json.dumps(bittrex.get_order_history()))
        else:
            out = json.loads(json.dumps(bittrex.get_order_history(args.market)))

        print(json.dumps(out, indent=4, sort_keys=True))

    if args.command == 'openorders':
        if args.market == 'all':
            out = json.loads(json.dumps(bittrex.get_open_orders()))
        else:
            out = json.loads(json.dumps(bittrex.get_open_orders(args.market)))
        print(json.dumps(out, indent=4, sort_keys=True))

if __name__ == "__main__":
    main(sys.argv[1:])
